server.port = 80
spring.datasource.platform=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url =jdbc:mysql://3.110.43.163:3306/dlerin
spring.datasource.username=master_admin
spring.datasource.password=madmin@123
#spring.datasource.url=jdbc:mysql://localhost:3306/dlerin
#spring.datasource.username=root
#spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.application.name=dlerin


#email sms
spring.mail.host=smtp.zoho.com
spring.mail.port=465
spring.mail.username=no_reply@kosuriers.com
spring.mail.password=Lunch@24
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.web.resources.static-locations=classpath:/static
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
#spring.mail.properties.mail.smtp.socketFactory.port=465

mrmason.textLocal.api-key=bpzNEtJGgKE-k8XO8wzS41OuCWD3EeJ5wx8LNL5wEf
mrmason.textLocal.sender= MRMASN
mrmason.textLocal.url=https://api.textlocal.in/send/?



#HTTPS
#server.ssl.key-store=classpath:dlerin_api_keystore.jks
#server.ssl.key-store-password=dlerin
#server.ssl.key-store-type=JKS
#server.ssl.key-alias=dlerin_api


application.security.jwt.secret-key=2lxEvcK9tEi3B86bCXOJndf6MH3g5tH5
application.security.jwt.expiration=86400000  
# a day
application.security.jwt.refresh-token.expiration=604800000
# 7 days
